CREATE TABLE role (
  id INT PRIMARY KEY AUTO_INCREMENT,
  label VARCHAR(100) NOT NULL
);

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role_id INT NOT NULL,
  FOREIGN KEY (role_id) REFERENCES role(id)
);


CREATE TABLE program(
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
image VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY(user_id) REFERENCES user(id)
);

CREATE TABLE user_program(
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
FOREIGN KEY(user_id) REFERENCES user(id),
program_id INT NOT NULL,
FOREIGN KEY(program_id) REFERENCES program(id)
);

CREATE TABLE exercise(
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  sets INT NOT NULL,
  repetition INT NOT NULL
);

CREATE TABLE program_exercise(
  id INT PRIMARY KEY AUTO_INCREMENT,
  program_id INT NOT NULL,
  FOREIGN KEY(program_id) REFERENCES program(id),
  exercise_id INT NOT NULL,
  FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

